#!/bin/bash
#
# The "watch" script watches the project's source directory
# and executes "make" whenever a file inside it changes.
# Note that "watch" produces a build for debugging (DEBUG=1).
# Use make clean && make to produce a release build instead.

indent() {
    sed 's/^/  /';
}

build() {
    make -s debug 2>&1 | indent;
    return ${PIPESTATUS[0]};
}

echo "Watching the project directory for changes."
while true; do
    # Watch all files and folders, but ignore .git, node_modules and so on.
    inotifywait -e modify,create,delete,move,attrib -rqq "." "@./.git" "@./node_modules" "@$BUILD_ROOT" "@./build" > /dev/null
    echo ""
    echo "Working directory changed ... "

    if build ; then
        echo "Build OK."
    else
        echo "Build failed."
    fi
done
